Repository push-protocol/push-smart-contracts, pull requests merged in 2024-01, with the labels that each got.

#244 230 migrate comm unit tests
  contracts/PushComm/PushCommV2_5.sol
  testFoundry/BaseTest.t.sol
  testFoundry/PushComm/unit_tests/SendingNotifications/SendNotifs.t.sol
  testFoundry/PushComm/unit_tests/SendingNotifications/SendNotifs.tree
  testFoundry/PushComm/unit_tests/SendingNotifications/SendNotifsViaSig.t.sol
  testFoundry/PushComm/unit_tests/SendingNotifications/SendNotifsViaSig.tree
  testFoundry/PushComm/unit_tests/SubscribeBySig/SubscribeBySig.t.sol
  testFoundry/PushComm/unit_tests/SubscribeBySig/SubscribeBySig.tree
  testFoundry/utils/Constants.sol
Labels: enhancement, priority-2

#246 Fuse network addition in deployment scripts
  .env.sample
  hardhat.config.js
  scripts/versioncontrol/2_deployEPNSCommV1.config.js
  scripts/versioncontrol/4_deployEPNSCommV2.config.js
  scripts/versioncontrol/6_deployEPNSCommV3.config.js
Labels: enhancement

#259 Solved the verification Bug and migrated the test
  contracts/PushComm/PushCommV2_5.sol
  contracts/PushCore/PushCoreV2_5.sol
  contracts/PushCore/PushCoreV2_Temp.sol
  test/PushCore/unit_tests/BasePushCoreTest.t.sol
  test/PushCore/unit_tests/ChannelVerifyTag/ChannelUnverification/ChannelUnverification.t.sol
  test/PushCore/unit_tests/ChannelVerifyTag/ChannelUnverification/ChannelUnverification.tree
  test/PushCore/unit_tests/ChannelVerifyTag/ChannelVerification/ChannelVerification.t.sol
  test/PushCore/unit_tests/ChannelVerifyTag/ChannelVerification/ChannelVerification.tree
  test/utils/Events.sol
Labels: bug, priority-1

#275 Added Gas Reports for Core and Comm
  foundry.toml
  test/gas_snapshots/CommGasSnapshots/AdminFunctions
  test/gas_snapshots/CommGasSnapshots/CompleteGasReport
  test/gas_snapshots/CommGasSnapshots/IncentivizedChat
  test/gas_snapshots/CommGasSnapshots/SendNotifs
  test/gas_snapshots/CommGasSnapshots/SubUnSubscribe
  test/gas_snapshots/CoreGasSnapshots/AdminFunctions
  test/gas_snapshots/CoreGasSnapshots/ChannelCreateDestroy
  test/gas_snapshots/CoreGasSnapshots/ChannelStateCycle
  test/gas_snapshots/CoreGasSnapshots/CompleteGasReport
  test/gas_snapshots/CoreGasSnapshots/IncentivizedChat
  test/gas_snapshots/CoreGasSnapshots/UpdateChannel
  test/gas_snapshots/CoreGasSnapshots/VerificationUnverifaction
Labels: priority-3

#276 273 additional changes in v25 contracts
  contracts/PushCore/PushCoreV2_Temp.sol
  scripts/Migration/FetchCore.js
  scripts/Migration/Migrate.js
  scripts/Migration/TestScript.js
Labels: priority-2
